//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class admininfo
    {
        public admininfo()
        {
            this.adminlogin = new HashSet<adminlogin>();
            this.hireinfo = new HashSet<hireinfo>();
        }
    
        public int id { get; set; }
        public string adminid { get; set; }
        public string adminname { get; set; }
        public Nullable<int> age { get; set; }
        public Nullable<System.DateTime> worktime { get; set; }
    
        public virtual ICollection<adminlogin> adminlogin { get; set; }
        public virtual ICollection<hireinfo> hireinfo { get; set; }
    }
}
