//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class hireinfo
    {
        public int id { get; set; }
        public string videoid { get; set; }
        public string clientid { get; set; }
        public string adminid { get; set; }
        public Nullable<int> isreturn { get; set; }
        public Nullable<System.DateTime> borrowtime { get; set; }
        public Nullable<System.DateTime> returntime { get; set; }
        public Nullable<double> rent { get; set; }
        public Nullable<System.DateTime> shouldtime { get; set; }
    
        public virtual admininfo admininfo { get; set; }
        public virtual clientinfo clientinfo { get; set; }
        public virtual videoinfo videoinfo { get; set; }
    }
}
