//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class videoinfo
    {
        public videoinfo()
        {
            this.hireinfo = new HashSet<hireinfo>();
            this.recommend = new HashSet<recommend>();
            this.review = new HashSet<review>();
        }
    
        public int id { get; set; }
        public string videoid { get; set; }
        public string videoname { get; set; }
        public Nullable<int> number { get; set; }
        public Nullable<double> price { get; set; }
        public Nullable<System.DateTime> buydate { get; set; }
        public string describe { get; set; }
        public string imageurl { get; set; }
        public Nullable<int> clickrate { get; set; }
    
        public virtual ICollection<hireinfo> hireinfo { get; set; }
        public virtual ICollection<recommend> recommend { get; set; }
        public virtual ICollection<review> review { get; set; }
    }
}
